CASCADEPATHFRONTALFACE = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/cascade/frontal_face.xml'
CASCADEPATHPROFILEFACE = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/cascade/profileface.xml'
DBPATH = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/db/images.db'
DBGENDER = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/db/gender.db'
IMAGESGENDERPATH = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/genderclassification'
IMAGESPATH = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/images'
# IMAGESPATH = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/images_101'
MODELFILE = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/model.mdl'
GENDERMODELFILE = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/gender.mdl'
LOG = '/home/lucas/PycharmProjects/facerecognitionLBPH/database/db/log.txt'
# CAMURL = 'http://admin:admin@192.168.253.212/video.cgi?.mjpg'
# CAMURL = 'http://supertratoressm.no-ip.net:7000/axis-cgi/mjpg/video.cgi'
CAMURL = 0
length = 100
width = length
IM_SIZE = (length, width)
